import Header from "@/components/views/header";
import Footer from "@/components/views/footer";

import "./globals.css";
import type { Metadata } from "next";
import { Sora } from "next/font/google";

const inter = Sora({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
